# Docker Compose for NillionVault (Nillion-only setup)
# Run with: docker-compose -f deploy/docker-compose.yml up --build

version: '3.8'

services:
  # Backend API
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      # Nillion Configuration (Set these in .env file or here)
      - BUILDER_PRIVATE_KEY=${BUILDER_PRIVATE_KEY}
      - NILCHAIN_URL=http://rpc.testnet.nilchain-rpc-proxy.nilogy.xyz
      - NILAUTH_URL=https://nilauth.sandbox.app-cluster.sandbox.nilogy.xyz
      - NILDB_NODES=https://nildb-stg-n1.nillion.network,https://nildb-stg-n2.nillion.network,https://nildb-stg-n3.nillion.network
      - NILLION_NETWORK=testnet
      
      # Server Configuration
      - NODE_ENV=production
      - PORT=3001
      - FRONTEND_URL=http://localhost:3000
    volumes:
      - ../backend:/app
      - /app/node_modules
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Frontend
  frontend:
    build:
      context: ../frontend/public
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=production
      # Update API URL to backend service name
      - NEXT_PUBLIC_API_URL=http://backend:3001
    depends_on:
      - backend
    volumes:
      - ../frontend/public:/app
      - /app/node_modules
    restart: unless-stopped
